theme: jekyll-theme-minimal
title: Monty Morris - Sound Engineer and Lighting Designer
description: I'm a passionate sound engineer and lighting designer, excited to contribute to the live events and touring industry. 
